apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.6.1
    spec:
      containers:
        - name: myjavacontainer
          image: maha4iac/myonlinebooking
          ports:
            - containerPort: 8080
